Repository Niconfisk/jogos-site-ifpb, pull requests merged in 2024-10, with the labels that each got.

#7 Enviando fotos
  assets/entrada.jpg
  assets/labfisica.jpg
  assets/piscina.jpg
  assets/refeitorio.jpg
Labels: design, resources, medium-priority

#8 Adiciona memória.js
  memoria.js
Labels: backend, JavaScript, high-priority

#9 Paleto de cores
  paleta de cores/estilo.css
Labels: design, CSS

#10 adiciona index.html
  index.html
Labels: enhancement, frontend, HTML, high-priority

#15 Adicionar as fotos dos locais
  assets/biblioteca.jpg
  assets/ginásio.jpg
  assets/lab.eletricidade eletronica.jpg
  assets/lab.informatica.jpg
  assets/lab.matematica.jpg
  assets/lab.materiais construçao.jpg
Labels: enhancement, resources, narrativa, medium-priority
